version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing backend dependencies..."
      - cd backend && npm install
      - echo "Installing frontend dependencies..."
      - cd ../frontend && npm install

  build:
    commands:
      - echo "Building backend..."
      - cd ../backend && npm run build
      - echo "Building frontend..."
      - cd ../frontend && npm run build

  post_build:
    commands:
      - echo "Current Directory:"
      - pwd
      - echo "Listing files in aws/cloudformation"
      - ls ../aws/cloudformation
      - echo "Deploying CloudFormation stack..."
      - pwd
      - aws cloudformation package --template-file ../aws/cloudformation/template.yml --output-template-file ../aws/cloudformation/packaged-template.yml --s3-bucket dev-assist-backend
      - pwd
      - aws cloudformation deploy --template-file ../aws/cloudformation/packaged-template.yml --stack-name DevAssistStack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - aws/cloudformation/packaged-template.yml
