AWSTemplateFormatVersion: '2010-09-09'
Description: Create S3 buckets for frontend and backend deployment

Resources:
  FrontendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dev-assist-portal
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  # S3 Bucket Policy to allow public access for the Frontend bucket
  FrontendS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendS3Bucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: s3:GetObject
            Resource: !Sub "${FrontendS3Bucket.Arn}/*"

  BackendS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: dev-assist-backend  # Unique bucket name
      VersioningConfiguration:
        Status: Enabled

Outputs:
  FrontendBucketWebsiteURL:
    Description: "Frontend S3 Bucket URL"
    Value: !GetAtt FrontendS3Bucket.WebsiteURL
